"""sync

Revision ID: 406949a940f0
Revises:
Create Date: 2026-05-14 21:18:18.486888

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore


# revision identifiers, used by Alembic.
revision: str = '406949a940f0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faces', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('test', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    # ### end Alembic commands ###
